name: Build and deploy Python project to Azure Function App - PIL Repro

 

on:

  push:

    branches:

      - master

  workflow_dispatch:

 

env:

  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root

  PYTHON_VERSION: "3.10" # set this to the python version to use (supports 3.6, 3.7, 3.8)

 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository

        uses: actions/checkout@v2

 

      - name: Setup Python version

        uses: actions/setup-python@v1

        with:

          python-version: ${{ env.PYTHON_VERSION }}

 

      - name: Upgrade pip and setuptools

        run: python -m pip install --upgrade pip setuptools

 

      - name: Install dependencies

        run: pip install -r requirements.txt

 

      # Optional: Add step to run tests here

 

      # Create an archive of the necessary files

      - name: Archive files

        run: tar -cvzf python-app.tar.gz -C . --exclude=./venv *

 

      # Upload the archived file as artifact

      - name: Upload artifact for deployment job

        uses: actions/upload-artifact@v2

        with:

          name: python-app

          path: python-app.tar.gz

 

      - name: Verify deployment package

        run: |

          tar -tzf python-app.tar.gz

 

  deploy:

    runs-on: ubuntu-latest

    needs: build

    environment:

      name: "Production"

      url: ${{ steps.deploy-to-function.outputs.webapp-url }}

 

    steps:

      - name: Download artifact from build job

        uses: actions/download-artifact@v2

        with:

          name: python-app

          path: .

 

      # Unarchive the downloaded artifact

      - name: Unarchive files

        run: tar -xvzf python-app.tar.gz

 

      - name: "Deploy to Azure Functions"

        uses: Azure/functions-action@v1

        id: deploy-to-function

        with:

          app-name: "PILRepro"

          slot-name: "Production"

          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

          publish-profile: ${{ secrets.APP_PUBLISH_PROFILE }}

          scm-do-build-during-deployment: false

          enable-oryx-build: false
